version: '3.0'

services:
  database:
    restart: always
    build: rinha-database/
    command: --lower_case_table_names=1
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
    ports:
      - "3306:3306"
    expose:
      - "3306"

volumes:
  db_data: