version: '3.8'
services:
  database:
    image: postgres:latest
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.5GB'
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha
    expose:
      - "5432"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 3s
      timeout: 5s
      retries: 10
    volumes:
      - type: bind
        source: ./init.sh
        target: /docker-entrypoint-initdb.d/init-extension.sh
    command: "postgres -c max_connections=200 -c shared_buffers=512MB -c effective_cache_size=1536MB -c maintenance_work_mem=128MB -c checkpoint_completion_target=0.9 -c wal_buffers=16MB -c default_statistics_target=100 -c random_page_cost=1.1 -c effective_io_concurrency=200 -c work_mem=1310kB -c huge_pages=off -c min_wal_size=1GB -c max_wal_size=4GB"
    networks:
      - rinha-network

networks:
  rinha-network:
