#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE EXTENSION pg_trgm;
	CREATE ROLE rinha LOGIN PASSWORD 'rinha';
	GRANT ALL PRIVILEGES ON DATABASE rinha TO rinha;
	GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO rinha;
EOSQL