CREATE TABLE IF NOT EXISTS PERSON (
    id UUID NOT NULL,
    nick_name VARCHAR(32) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    date_of_birth DATE NOT NULL,
    stack VARCHAR(32)[],
    search TEXT NOT NULL,
    CONSTRAINT ID_PK PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS IDX_PERSON_SEARCH ON PERSON USING GIST (search GIST_TRGM_OPS(SIGLEN=64));